apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bikeshare-ml
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api

    spec: 
      containers:
      - name: bikeshare-ml
        image: kaushiktd/bike_sharing_api
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports: 
          - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
spec:
  selector:
    app: fast-api
  ports:
  - port: 8001
    targetPort: 8001
  type: LoadBalancer          

              
